/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#d2bbff",
        "on-tertiary": "#620040",
        "surface-container-high": "#222a3d",
        "tertiary-fixed-dim": "#ffafd3",
        "on-secondary-container": "#00424e",
        "on-background": "#dae2fd",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "primary": "#d2bbff",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-fixed": "#001f26",
        "on-tertiary-fixed": "#3d0026",
        "secondary": "#4cd7f6",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "primary-fixed-dim": "#d2bbff",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "on-primary": "#3f008e",
        "surface-dim": "#0b1326",
        "outline": "#958da1",
        "inverse-primary": "#732ee4",
        "on-secondary": "#003640",
        "surface": "#0b1326",
        "surface-container-low": "#131b2e",
        "outline-variant": "#4a4455",
        "primary-fixed": "#eaddff",
        "secondary-fixed": "#acedff",
        "on-surface": "#dae2fd",
        "secondary-container": "#03b5d3",
        "on-tertiary-fixed-variant": "#85145a",
        "tertiary-container": "#ae397b",
        "surface-container-lowest": "#060e20",
        "on-primary-container": "#ede0ff",
        "surface-container-highest": "#2d3449",
        "tertiary": "#ffafd3",
        "error-container": "#93000a",
        "on-surface-variant": "#ccc3d8",
        "primary-container": "#7c3aed",
        "on-primary-fixed-variant": "#5a00c6",
        "on-tertiary-container": "#ffdce9",
        "surface-container": "#171f33",
        "error": "#ffb4ab",
        "on-primary-fixed": "#25005a",
        "tertiary-fixed": "#ffd8e7",
        "background": "#0b1326"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "sm": "12px",
        "xl": "80px",
        "margin-mobile": "16px",
        "lg": "48px",
        "gutter": "24px",
        "xs": "4px",
        "base": "8px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "display-sm": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
